### PR TITLE
Update eslint-plugin-react-hooks

### PR DESCRIPTION
**Pull request by kevinbarabash**
In preparation for upgrading React in webapp, I'm updating this plugin so that we can enable some lint rules at the same time that we upgrade React.

Issue: none

Test plan: n/a, we have no code using hooks yet

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@aalzanki my understanding is that mobile isn't using `khan-linter` any more.  Is that correct?

**Comment by kevinbarabash** [comment]
Abandoning in preference of https://phabricator.khanacademy.org/D62270.

**Comment by aalzanki** [comment]
@kevinbarabash not sure. @jeremywiebe is mobile still using `khan-linter`?

**Comment by jeremywiebe** [comment]
@aalzanki We don't use the `khan-linter` commands, but we do still use the ESLint RC file from `khan-linter`.

image
☝️ from our mobile `.eslintrc`

**Pull request closed without merging**
