### PR TITLE
Add prettier support to khan-linter

### PR DESCRIPTION
**Pull request by jeresig**
This diff adds prettier support to khan-linter. This comes in a few forms:

1) The eslint style rules have been updated to align with prettier's rules. They tend to align pretty well with how we have things right now in webapp, which is good. I also removed the `max-len` rule as we'll be using `prettier` to enforce line length limits. Having an additional line-length rules is confusing and only serves to create confusion. In practice, in our code base, we're ok with long lines (like strings - such as URLs, SVG paths, etc.) but not long code. Prettier fixes the issue of long code and leaves the other pieces intact without creating frustration (we'll no longer have to add `// @Nolint` to all the long lines in our files).
2) The prettier plugin was added to eslint, along with a new `eslintrc.prettier` config which means that we can use eslint to automatically fix prettier syntax changes with eslint. For example we can `eslint --fix some-js-file.js` and eslint will automatically update the file with the new syntax, outputting any additional lint errors. Additionally, if not run with `--fix` eslint will show errors for all of the differences that prettier would fix.
3) Support for `arc diff`/`arc lint` auto-patching the prettier fixes was added. If you run `arc diff` against a piece of (un-pretty) JavaScript code a patch will be provided which you can opt to apply to your file (or diff, as the case may be).

I should note that I also had to update `eslint` and `babel-eslint` to support the prettier integration.

Test Plan:
I ran `ka-lint javascript` in webapp and confirmed that it passed.

I then changed webapp's `.eslintrc` file to point to `eslintrc.prettier` and ran `ka-lint` against a JavaScript file and saw that it output a bunch of syntax errors and diff which I could apply to the file to update it to match the prettier style. Accepting it updated the file and the linter passed.

I also made a change to a JavaScript file and ran `arc lint`. It output a list of prettier syntax errors and then gave me the option to apply a patch to my file, updating it. Doing so updated it to match the prettier style.

(This diff was too big to submit via Phabricator. Pretty much all of the relevant changes are at the start of the diff, save for the package.json at the very end.)

### CODE REVIEW

**Comment by jeresig** [comment]
An open question, which I could also resolve in this diff: I'd like to expose the `eslint --fix` command so that we can use it in webapp and other repos. What's the best way to do this? I could make a new command (`ka-prettier`?) but I'm not sure what would be needed to get that into folks config files to use it. Alternatively I could add it as an option to `ka-lint` like `ka-lint --fix` - which just passes through to `eslint`. Thoughts?

**Comment by kevinbarabash** [comment]
I was looking at passing `eslint`'s fixes through to `ka-lint`'s existing auto-fix infrastructure.  It looked like we'd have to change how we're calling `eslint`.  Instead of calling `eslint` from the command line we'd want to call it using the JavaScript API to get the proposed fixes.  This is to avoid changing the files in place outside of a git commit.  I think this would be best handled as a separate diff.

**Comment by jeresig** [comment]
@kevinbarabash I've already done this - this is part of this commit! Specifically the changes to linters.py and lint_util.py. Everything is fully hooked in to ka-lint (and thus arc lint/arc diff's auto-fix functionality).

**Comment by kevinbarabash** [comment]
> I've already done this - this is part of this commit!

Awesome.  Sorry for commenting without reading the code.  I'll have a look at it Monday.

> My question, in the comment, was specifically around if we wanted to provide a utility for cleaning up files (either individually, or in bulk) outside of the normal commit process.

I could see that being useful when updating lint rules or changing prettier settings.

**Comment by csilvers** [comment]
@kevinbarabash I think you were thinking about flow, not eslint?  We already only run eslint over the requested files.  It's flow we have to run it over everything and then filter.

@jeresig I like the idea of just passing a `fix` flag to ka-lint.  That way we can apply other auto-fixes as well: I think pep8 has some autofixing maybe?, that we've never used?  (Aside: I wish there was a better way to integrate the tools' autofixing with arc's.)  We may want to name the flag carefully to distinguish it from the existing `--propose-arc-fixes`.

**Pull request merged**
