### PR TITLE
Add eslint-plugin-import

### PR DESCRIPTION
**Pull request by kevinbarabash**
Summary:
This eslint plugin has some useful rules.  In particular we'd like to
make use of the "extensions" rule to ensure that all imports have
extensions.  In a recent code review we spotted an import that was
missing its extension.  I'll add this rule to .eslintrc in webapp
in a separate commit.

The files in this PR were generated by running `yarn install eslint-plugin-import`.
Version 2.18.0 of this plugin was installed.

NOTE: This was created as a PR, b/c arc took a long time linting all 
the files and then bail b/c the request size was too big.  Even when
passing `--less-context` to `arc`, it still failed.

Test Plan:
- add `"import/extensions": ["error", "always", {"ignorePackages": true} ],` to .eslintrc in webapp
- check that violations in course-intro-custom-button-options.jsx (in webapp) are flagged

Reviewers: #fe-infra

### CODE REVIEW

**Comment by csilvers** [comment]
> NOTE: This was created as a PR, b/c arc took a long time linting all
> the files and then bail b/c the request size was too big.

FWIW, you can do `arc diff --nounit --less-context` to get around these problems.  (Though maybe --less-context won't work in this case.)

**Comment by csilvers** [comment]
This diff is unreadable in github. :-(  Can you list what files you changes besides adding the new node_modules flies?  Or did you just change node_modules?

**Comment by kevinbarabash** [comment]
@csilvers I've updated the summary with more details of what was installed into node_modules.  The only file besides node_modules that was modified was package.json.  

Here's the diff for package.json:
```
diff --git a/package.json b/package.json
index a5f679e9..650d0965 100644
--- a/package.json
+++ b/package.json
@@ -14,11 +14,12 @@
     "eslint-config-prettier": "3.1.0",
     "eslint-plugin-flowtype": "3.2.0",
     "eslint-plugin-graphql": "2.1.1",
-    "graphql": "0.13.2",
+    "eslint-plugin-import": "^2.18.0",
     "eslint-plugin-jsx-a11y": "^6.1.2",
     "eslint-plugin-prettier": "3.0.0",
     "eslint-plugin-react": "7.11.1",
     "eslint-plugin-react-native-animation-linter": "0.1.2",
+    "graphql": "0.13.2",
     "khan-lesshint": "0.1.0",
     "prettier": "1.15.1",
     "utf8": "3.0.0"
```

I tried `--less-context`, but 3100 files is still too much.  I agree that this diff is unreadable.  This is why I was asking about not checking in `node_modules` in the future.  It's a pain to create these diffs and a pain to review and there doesn't seem to be much benefit in doing so.

**Comment by benjaminjkraft** [comment]
I don't know that I understand why this is a good idea, so I'll just say: before landing, please make sure you've fixed all the violations in webapp, deployed that commit, and PSAed so folks aren't surprised if new ones break.  (Just a reminder that we need a better linting process >.< .)

**Comment by csilvers** [comment]
Typically folks update the vendored code as an audit, and then make a real phab diff just for the contentful changes on top of it.  There's no need to review this that I can see.

**Comment by kevinbarabash** [comment]
I can merge this PR because I've haven't updated any of the eslintrc files in this diff, I've just added the plugin.

**Pull request merged**
